#!/usr/bin/env bash
#-------------------------------------------
# Kraken2 analysis with the sbatch.kraken script
sbatch kraken.sbatch

#-------------------------------------------
# Krona visualization
# combined.kreport (for all samples kreports combination, if you want a Krona graph of all samples) (recommended to have combined_final.kreport in the same directory as the rest of the kreports for kreport2krona.py)
python <FULL_PATH_TO_COMBINE_KREPORTS.PY> -r <KREPORT_FILES> -o <COMBINED_FINAL.KREPORT>

# kreport2krona.py
for f in <KREPORTS_FULL_PATH>/*.report; do
  base=$(basename "$f" .report)
  echo "Generating ${base}.krona..."
  python <FULL_PATH_TO_KREPORT2KRONA.PY> -r "$f" -o <OUTPUT_DIR>/"${base}.krona"
done

# ktImportText (visualization - downloadable .html files with Krona graphs)
for f in <KRONA_FILES_FULL_PATH>/*.krona; do
  base=$(basename "$f" .krona)
  echo "Generating ${base}.html..."
  ktImportText "$f" -o <OUTPUT_DIR>/"${base}.html"
done

#-------------------------------------------
# keep only homo sapiens reads with sbatch.filter_reads script
sbatch filter_reads.sbatch

for f in <OUTPUT_DIR_OF_FILTERED_READS>/*_clean_R*.fq; do
    echo "Compressing $f"
    gzip "$f"
done

bash fix_fasta_to_fastq.sh

#-------------------------------------------
# nf-core/rna-seq with rna-seq.sbatch
sbatch lncpipe.sbatch

#-------------------------------------------
# prep for CPAT and DE
# unzip the reference
gunzip -c <REFERENCE.FA.GZ>

# extract transcripts
conda activate env_nf
gffread -w transcripts_full.fa \
  -g <REFERENCE.FA> \
   <OUTPUT_DIR_OF_LNCPIPE.SBATCH>/gffcompare/stringtie_merged/stringtie_merged.annotated.gtf

# run CPAT
conda activate env_cpat_py2
# CPAT models need to be downloaded
cpat.py -g transcripts_full.fa \
        -x <HUMAN_HEXAMER.TSV> \
        -d <HUMAN_LOGITMODEL.RDATA> \
        -o cpat_results_full.txt

conda activate env_nf
# includes cpat results into a transcript file generated by nf-core/lncpipe (lncpipe.sbatch)
chmod +x transcript_characterization.py
./transcript_characterization.py
